version: '3'
services:
  frontend:
    ports:
      - "9000:80"
  
  backend:
    environment:
      - CONFIG2_PATH=${HOME}/OFF_DATA/etc/Config2.pm
      - SKIP_SYMLINKS=1
    volumes:
      - ${HOME}/OFF_DATA:/home/user/OFF_DATA:rw
    command: ["bash", "-c", "cp -f ${HOME}/OFF_DATA/etc/Config2.pm /opt/product-opener/lib/ProductOpener/Config2.pm && apache2-foreground"]
  
  incron:
    environment:
      - CONFIG2_PATH=${HOME}/OFF_DATA/etc/Config2.pm
      - SKIP_SYMLINKS=1
    volumes:
      - ${HOME}/OFF_DATA:/home/user/OFF_DATA:rw
    command: ["bash", "-c", "cp -f ${HOME}/OFF_DATA/etc/Config2.pm /opt/product-opener/lib/ProductOpener/Config2.pm && incrond-foreground"]

  minion:
    environment:
      - CONFIG2_PATH=${HOME}/OFF_DATA/etc/Config2.pm
      - SKIP_SYMLINKS=1
    volumes:
      - ${HOME}/OFF_DATA:/home/user/OFF_DATA:rw