# This workflow aims at checking that no link nor image is broken in the content pages.
# The action uses a recursive scan to avoid large arglists.
# This is a test version that can be triggered manually for local testing with act.
name: Link Rot Check (Test)
on:
  schedule:
    - cron: '0 0 * * 0'      # Runs every Sunday at midnight UTC
  workflow_dispatch:        # Allows manual triggering for testing
    inputs:
      debug:
        description: 'Enable debug output'
        required: false
        default: 'false'
        type: boolean

jobs:
  link-rot:
    concurrency:
      group: link-rot-check-test
      cancel-in-progress: true
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run link-rot check
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          # Scan directories and markdown files, hide progress
          args: --base . --verbose --no-progress --exclude-loopback --exclude-private 'html/' 'templates/' './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output results
        if: always()
        run: |
          echo "Link rot check completed"
          if [ -f lychee/out.md ]; then
            echo "Results found in lychee/out.md"
            cat lychee/out.md
          else
            echo "No results file found"
          fi
