# Runs a link check on modified markdown and HTML content files on push
name: Link Rot on Push
on:
  push:
    # Only trigger when markdown or HTML pages change
    paths:
      - '**/*.md'
      - 'html/**/*.html'
      - 'templates/**/*.html'

jobs:
  link-rot-changed:
    concurrency:
      group: link-rot-on-push
      cancel-in-progress: true
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get modified files
        id: get_files
        run: |
          # collect all donate page HTML filenames
          html_files=$(find html/donate -type f -name '*.html' -exec basename {} \;)
          # join filenames into space-separated string
          html_files=$(echo "$html_files" | xargs)
          # build comma-separated list including docs
          file_list="CONTRIBUTING.md,README.md,${html_files// /,}"
          echo "::set-output name=all_files::$file_list"
          echo "$file_list"

      - name: Run link check
        if: steps.get_files.outputs.all_files != ''
        uses: paramt/url-checker@master
        id: check
        with:
          files: ${{ steps.get_files.outputs.all_files }}

      - name: Create GitHub Check
        if: steps.get_files.outputs.all_files != ''
        uses: LouisBrunner/checks-action@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Link Rot
          status: completed
          conclusion: ${{ steps.check.outputs.conclusion }}
          output: ${{ steps.check.outputs.output }}
